import type { FoodItem } from '../types';

export const foodDb: FoodItem[] = [
  { name: '熟米饭', gramsPerFist: 200, caloriesPer100g: 116, foodType: 'normal', category: 'staple' },
  { name: '馒头', gramsPerFist: 150, caloriesPer100g: 223, foodType: 'normal', category: 'staple' },
  { name: '面条(熟)', gramsPerFist: 200, caloriesPer100g: 110, foodType: 'normal', category: 'staple' },
  { name: '燕麦', gramsPerFist: 80, caloriesPer100g: 377, foodType: 'normal', category: 'staple' },
  { name: '全麦面包', gramsPerFist: 100, caloriesPer100g: 246, foodType: 'normal', category: 'staple' },
  { name: '红薯', gramsPerFist: 200, caloriesPer100g: 86, foodType: 'normal', category: 'staple' },
  { name: '玉米', gramsPerFist: 200, caloriesPer100g: 112, foodType: 'normal', category: 'staple' },
  { name: '饺子', gramsPerFist: 150, caloriesPer100g: 200, foodType: 'normal', category: 'staple' },
  { name: '包子', gramsPerFist: 150, caloriesPer100g: 220, foodType: 'normal', category: 'staple' },
  { name: '鸡胸肉', gramsPerFist: 150, caloriesPer100g: 120, foodType: 'normal', category: 'meat' },
  { name: '鸡腿肉', gramsPerFist: 150, caloriesPer100g: 150, foodType: 'normal', category: 'meat' },
  { name: '猪瘦肉', gramsPerFist: 150, caloriesPer100g: 143, foodType: 'stir_fried', category: 'meat' },
  { name: '五花肉', gramsPerFist: 150, caloriesPer100g: 349, foodType: 'stir_fried', category: 'meat' },
  { name: '牛肉(瘦)', gramsPerFist: 150, caloriesPer100g: 106, foodType: 'normal', category: 'meat' },
  { name: '牛腩', gramsPerFist: 150, caloriesPer100g: 200, foodType: 'stir_fried', category: 'meat' },
  { name: '鱼肉', gramsPerFist: 150, caloriesPer100g: 100, foodType: 'normal', category: 'meat' },
  { name: '虾仁', gramsPerFist: 150, caloriesPer100g: 48, foodType: 'normal', category: 'meat' },
  { name: '排骨', gramsPerFist: 150, caloriesPer100g: 264, foodType: 'stir_fried', category: 'meat' },
  { name: '腊肉/香肠', gramsPerFist: 100, caloriesPer100g: 498, foodType: 'stir_fried', category: 'meat' },
  { name: '青菜(炒)', gramsPerFist: 100, caloriesPer100g: 60, foodType: 'stir_fried', category: 'vegetable' },
  { name: '西兰花', gramsPerFist: 100, caloriesPer100g: 36, foodType: 'normal', category: 'vegetable' },
  { name: '番茄', gramsPerFist: 150, caloriesPer100g: 18, foodType: 'normal', category: 'vegetable' },
  { name: '黄瓜', gramsPerFist: 150, caloriesPer100g: 16, foodType: 'normal', category: 'vegetable' },
  { name: '土豆', gramsPerFist: 200, caloriesPer100g: 81, foodType: 'normal', category: 'vegetable' },
  { name: '茄子(炒)', gramsPerFist: 150, caloriesPer100g: 70, foodType: 'stir_fried', category: 'vegetable' },
  { name: '豆角(炒)', gramsPerFist: 100, caloriesPer100g: 65, foodType: 'stir_fried', category: 'vegetable' },
  { name: '鸡蛋(1个)', gramsPerFist: 50, caloriesPer100g: 140, foodType: 'normal', category: 'egg_dairy' },
  { name: '纯牛奶', gramsPerFist: 250, caloriesPer100g: 60, foodType: 'normal', category: 'egg_dairy' },
  { name: '酸奶', gramsPerFist: 200, caloriesPer100g: 80, foodType: 'normal', category: 'egg_dairy' },
  { name: '奶酪', gramsPerFist: 50, caloriesPer100g: 328, foodType: 'normal', category: 'egg_dairy' },
  { name: '苹果(1个)', gramsPerFist: 200, caloriesPer100g: 52, foodType: 'normal', category: 'fruit' },
  { name: '香蕉(1根)', gramsPerFist: 120, caloriesPer100g: 91, foodType: 'normal', category: 'fruit' },
  { name: '橙子', gramsPerFist: 200, caloriesPer100g: 47, foodType: 'normal', category: 'fruit' },
  { name: '葡萄', gramsPerFist: 200, caloriesPer100g: 69, foodType: 'normal', category: 'fruit' },
  { name: '西瓜', gramsPerFist: 300, caloriesPer100g: 30, foodType: 'normal', category: 'fruit' },
  { name: '薯片', gramsPerFist: 50, caloriesPer100g: 530, foodType: 'fried', category: 'snack' },
  { name: '饼干', gramsPerFist: 50, caloriesPer100g: 433, foodType: 'normal', category: 'snack' },
  { name: '蛋糕', gramsPerFist: 100, caloriesPer100g: 347, foodType: 'normal', category: 'snack' },
  { name: '巧克力', gramsPerFist: 50, caloriesPer100g: 546, foodType: 'normal', category: 'snack' },
  { name: '坚果', gramsPerFist: 50, caloriesPer100g: 600, foodType: 'normal', category: 'snack' },
  { name: '冰淇淋', gramsPerFist: 100, caloriesPer100g: 200, foodType: 'normal', category: 'snack' },
];

export const foodCategories = [
  { key: 'all', label: '全部' },
  { key: 'staple', label: '主食' },
  { key: 'meat', label: '肉类' },
  { key: 'vegetable', label: '蔬菜' },
  { key: 'egg_dairy', label: '蛋奶' },
  { key: 'fruit', label: '水果' },
  { key: 'snack', label: '零食' },
];
